# -*- coding: utf-8 -*-
"""
/***************************************************************************
 Compass Traverse GIS
                                 A QGIS plugin
 Compass survey import, traverse adjustment, and GIS output for QGIS
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2026-02-15
        copyright            : (C) 2026 by Hideharu Masai
        email                : hideharumasai@void.mints.ne.jp
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load CompassTraverseGis class from file compass_traverse_gis.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    from .compass_traverse_gis import CompassTraverseGis

    return CompassTraverseGis(iface)
