# -*- coding: utf-8 -*-
"""
/***************************************************************************
 Compass Traverse GIS
                                 A QGIS plugin
 Compass survey import, traverse adjustment, and GIS output for QGIS
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                              -------------------
        begin                : 2026-02-15
        git sha              : $Format:%H$
        copyright            : (C) 2026 by Hideharu Masai
        email                : hideharumasai@void.mints.ne.jp
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
"""
from qgis.PyQt.QtCore import QSettings, QTranslator, QCoreApplication, Qt
from qgis.PyQt.QtGui import QIcon
from qgis.PyQt.QtWidgets import QAction, QDialog, QDockWidget, QVBoxLayout

import os.path

from .compass_traverse_gis_dockwidget import CompassTraverseGisDockWidget


class CompassTraverseGis:
    """QGIS Plugin Implementation."""

    def __init__(self, iface):
        """Constructor.

        :param iface: An interface instance that will be passed to this class
            which provides the hook by which you can manipulate the QGIS
            application at run time.
        :type iface: QgsInterface
        """
        # Save reference to the QGIS interface
        self.iface = iface

        # initialize plugin directory
        self.plugin_dir = os.path.dirname(__file__)
        self.translator = None
        self._language_setting_key = "CompassTraverseGis/language"
        self._separate_window_key = "CompassTraverseGis/separate_window"
        self._dialog_geometry_key = "CompassTraverseGis/window_geometry"
        self.current_language_code = self._preferred_language_code()
        self._apply_language(self.current_language_code, persist=False)

        # Declare instance attributes
        self.actions = []
        self.menu = self.tr(u'&Compass Traverse GIS')

        # UI panel and its two possible hosts (docked / separate window)
        self.panel = None
        self.dock = None
        self.dialog = None
        self._switching_container = False

    def _preferred_language_code(self):
        stored_language = QSettings().value(self._language_setting_key, "", type=str)
        if stored_language:
            return stored_language[0:2]
        locale = QSettings().value("locale/userLocale", "en", type=str)
        return locale[0:2] or "en"

    def _apply_language(self, language_code, persist=True):
        normalized_code = (language_code or "en")[0:2]
        if self.translator is not None:
            QCoreApplication.removeTranslator(self.translator)
            self.translator = None

        locale_path = os.path.join(
            self.plugin_dir,
            "i18n",
            "compass_traverse_gis_{}.qm".format(normalized_code),
        )
        if normalized_code != "en" and os.path.exists(locale_path):
            translator = QTranslator()
            if translator.load(locale_path):
                QCoreApplication.installTranslator(translator)
                self.translator = translator

        self.current_language_code = normalized_code
        if persist:
            QSettings().setValue(self._language_setting_key, normalized_code)

    def set_language(self, language_code):
        self._apply_language(language_code)
        if self.panel is not None:
            self.panel.apply_language(self.current_language_code)
        title = self.tr(u'Compass Traverse GIS')
        if self.dock is not None:
            self.dock.setWindowTitle(title)
        if self.dialog is not None:
            self.dialog.setWindowTitle(title)

    # noinspection PyMethodMayBeStatic
    def tr(self, message):
        """Get the translation for a string using Qt translation API.

        We implement this ourselves since we do not inherit QObject.

        :param message: String for translation.
        :type message: str, QString

        :returns: Translated version of message.
        :rtype: QString
        """
        # noinspection PyTypeChecker,PyArgumentList,PyCallByClass
        return QCoreApplication.translate('CompassTraverseGis', message)

    def add_action(
        self,
        icon_path,
        text,
        callback,
        enabled_flag=True,
        add_to_menu=True,
        add_to_toolbar=True,
        status_tip=None,
        whats_this=None,
        parent=None,
    ):
        """Add a toolbar icon to the toolbar.

        :param icon_path: Path to the icon for this action. Can be a resource
            path (e.g. ':/plugins/foo/bar.png') or a normal file system path.
        :type icon_path: str

        :param text: Text that should be shown in menu items for this action.
        :type text: str

        :param callback: Function to be called when the action is triggered.
        :type callback: function

        :param enabled_flag: A flag indicating if the action should be enabled
            by default. Defaults to True.
        :type enabled_flag: bool

        :param add_to_menu: Flag indicating whether the action should also
            be added to the menu. Defaults to True.
        :type add_to_menu: bool

        :param add_to_toolbar: Flag indicating whether the action should also
            be added to the toolbar. Defaults to True.
        :type add_to_toolbar: bool

        :param status_tip: Optional text to show in a popup when mouse pointer
            hovers over the action.
        :type status_tip: str

        :param parent: Parent widget for the new action. Defaults None.
        :type parent: QWidget

        :param whats_this: Optional text to show in the status bar when the
            mouse pointer hovers over the action.

        :returns: The action that was created. Note that the action is also
            added to self.actions list.
        :rtype: QAction
        """

        icon = QIcon(icon_path)
        action = QAction(icon, text, parent)
        action.triggered.connect(callback)
        action.setEnabled(enabled_flag)

        if status_tip is not None:
            action.setStatusTip(status_tip)

        if whats_this is not None:
            action.setWhatsThis(whats_this)

        if add_to_toolbar:
            self.iface.addVectorToolBarIcon(action)

        if add_to_menu:
            self.iface.addPluginToVectorMenu(self.menu, action)

        self.actions.append(action)

        return action

    def initGui(self):
        """Create the menu entries and toolbar icons inside the QGIS GUI."""

        icon_path = os.path.join(os.path.dirname(__file__), 'icon.png')
        self.add_action(
            icon_path,
            text=self.tr(u'Compass Traverse GIS'),
            callback=self.run,
            parent=self.iface.mainWindow(),
        )

    # --------------------------------------------------------------------------

    def onClosePlugin(self):
        """Cleanup when the panel itself is closed (rare; disposal is normally via unload)."""
        self._dispose_all()

    def unload(self):
        """Removes the plugin menu item and icon from QGIS GUI."""

        if self.translator is not None:
            QCoreApplication.removeTranslator(self.translator)
            self.translator = None

        self._dispose_all()

        for action in self.actions:
            self.iface.removePluginVectorMenu(
                self.tr(u'&Compass Traverse GIS'),
                action,
            )
            self.iface.removeVectorToolBarIcon(action)

    # --------------------------------------------------------------------------

    def _separate_window_enabled(self):
        return QSettings().value(self._separate_window_key, False, type=bool)

    def _ensure_panel(self):
        if self.panel is None:
            self.panel = CompassTraverseGisDockWidget(
                iface=self.iface,
                plugin=self,
            )
            self.iface.mainWindow().installEventFilter(self.panel)
            self.panel.closingPlugin.connect(self.onClosePlugin)

    def _create_dock(self):
        if self.dock is not None:
            return
        self._ensure_panel()
        self.dock = QDockWidget(self.tr(u'Compass Traverse GIS'), self.iface.mainWindow())
        self.dock.setObjectName('CompassTraverseGisDock')
        # No DockWidgetFloatable: native float is the Windows/Qt6 ghost-artifact path.
        self.dock.setFeatures(
            QDockWidget.DockWidgetFeature.DockWidgetClosable
            | QDockWidget.DockWidgetFeature.DockWidgetMovable
        )
        self.dock.setAllowedAreas(
            Qt.DockWidgetArea.TopDockWidgetArea
            | Qt.DockWidgetArea.BottomDockWidgetArea
        )
        self.dock.setWidget(self.panel)
        self.panel.set_separate_window_checked(False)
        self.iface.addDockWidget(Qt.DockWidgetArea.BottomDockWidgetArea, self.dock)
        self.panel.show()

    def _create_dialog(self):
        if self.dialog is not None:
            return
        self._ensure_panel()
        self.dialog = QDialog(None, Qt.WindowType.Window)
        self.dialog.setObjectName('CompassTraverseGisWindow')
        self.dialog.setWindowTitle(self.tr(u'Compass Traverse GIS'))
        layout = QVBoxLayout(self.dialog)
        layout.setContentsMargins(0, 0, 0, 0)
        layout.addWidget(self.panel)
        self.panel.set_separate_window_checked(True)
        self.panel.show()
        geometry = QSettings().value(self._dialog_geometry_key, None)
        if geometry:
            self.dialog.restoreGeometry(geometry)
        else:
            self.dialog.resize(1200, 600)
        self.dialog.finished.connect(self._on_dialog_finished)

    def _save_dialog_geometry(self):
        if self.dialog is not None:
            QSettings().setValue(
                self._dialog_geometry_key, self.dialog.saveGeometry()
            )

    def _on_dialog_finished(self, *_args):
        # Closing the separate window just hides it; the plugin stays loaded.
        if not self._switching_container:
            self._save_dialog_geometry()

    def _destroy_dock(self):
        if self.dock is None:
            return
        self.dock.setWidget(None)
        self.iface.removeDockWidget(self.dock)
        self.dock.deleteLater()
        self.dock = None

    def _destroy_dialog(self):
        if self.dialog is None:
            return
        self._save_dialog_geometry()
        layout = self.dialog.layout()
        if layout is not None:
            layout.removeWidget(self.panel)
        self.panel.setParent(None)
        self.dialog.hide()
        self.dialog.deleteLater()
        self.dialog = None

    def set_separate_window(self, enabled):
        """Swap the panel between a docked QDockWidget and a top-level QDialog."""
        QSettings().setValue(self._separate_window_key, bool(enabled))
        self._ensure_panel()
        self._switching_container = True
        try:
            if enabled:
                self._destroy_dock()
                self._create_dialog()
                self.dialog.show()
                self.dialog.raise_()
                self.dialog.activateWindow()
            else:
                self._destroy_dialog()
                self._create_dock()
                self.panel.show()
                self.dock.show()
                self.dock.raise_()
        finally:
            self._switching_container = False

    def hide_container(self):
        if self.dialog is not None:
            self.dialog.hide()
        elif self.dock is not None:
            self.dock.hide()

    def run(self):
        """Show the panel in its configured host, creating it on first use."""
        self._ensure_panel()

        first_show = self.dock is None and self.dialog is None
        if first_show:
            if self._separate_window_enabled():
                self._create_dialog()
            else:
                self._create_dock()
        else:
            self.panel._clear_preview_layers()
            self.panel.apply_language(self.current_language_code)

        if self.dialog is not None:
            self.dialog.show()
            self.dialog.raise_()
            self.dialog.activateWindow()
        elif self.dock is not None:
            if not first_show and self.dock.isVisible():
                self.dock.hide()
            else:
                self.dock.show()
                self.dock.raise_()

    def _dispose_all(self):
        if self.panel is None and self.dock is None and self.dialog is None:
            return
        if self.panel is not None:
            self.iface.mainWindow().removeEventFilter(self.panel)
            try:
                self.panel.closingPlugin.disconnect(self.onClosePlugin)
            except TypeError:
                pass
        self._destroy_dialog()
        self._destroy_dock()
        if self.panel is not None:
            self.panel.close()
            self.panel.deleteLater()
            self.panel = None
