# -*- coding: utf-8 -*-
"""
/***************************************************************************
 Compass Traverse GIS
                                 A QGIS plugin
 Compass survey import, traverse adjustment, and GIS output for QGIS
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                              -------------------
        begin                : 2026-02-15
        git sha              : $Format:%H$
        copyright            : (C) 2026 by Hideharu Masai
        email                : hideharumasai@void.mints.ne.jp
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
"""
from qgis.PyQt.QtCore import QSettings, QTranslator, QCoreApplication, Qt
from qgis.PyQt.QtGui import QIcon
from qgis.PyQt.QtWidgets import QAction

import os.path

from .compass_traverse_gis_dockwidget import CompassTraverseGisDockWidget


class CompassTraverseGis:
    """QGIS Plugin Implementation."""

    def __init__(self, iface):
        """Constructor.

        :param iface: An interface instance that will be passed to this class
            which provides the hook by which you can manipulate the QGIS
            application at run time.
        :type iface: QgsInterface
        """
        # Save reference to the QGIS interface
        self.iface = iface

        # initialize plugin directory
        self.plugin_dir = os.path.dirname(__file__)
        self.translator = None
        self._language_setting_key = "CompassTraverseGis/language"
        self.current_language_code = self._preferred_language_code()
        self._apply_language(self.current_language_code, persist=False)

        # Declare instance attributes
        self.actions = []
        self.menu = self.tr(u'&Compass Traverse GIS')

        #print "** INITIALIZING CompassTraverseGis"

        self.pluginIsActive = False
        self.dockwidget = None

    def _preferred_language_code(self):
        stored_language = QSettings().value(self._language_setting_key, "", type=str)
        if stored_language:
            return stored_language[0:2]
        locale = QSettings().value("locale/userLocale", "en", type=str)
        return locale[0:2] or "en"

    def _apply_language(self, language_code, persist=True):
        normalized_code = (language_code or "en")[0:2]
        if self.translator is not None:
            QCoreApplication.removeTranslator(self.translator)
            self.translator = None

        locale_path = os.path.join(
            self.plugin_dir,
            "i18n",
            "compass_traverse_gis_{}.qm".format(normalized_code),
        )
        if normalized_code != "en" and os.path.exists(locale_path):
            translator = QTranslator()
            if translator.load(locale_path):
                QCoreApplication.installTranslator(translator)
                self.translator = translator

        self.current_language_code = normalized_code
        if persist:
            QSettings().setValue(self._language_setting_key, normalized_code)

    def set_language(self, language_code):
        self._apply_language(language_code)
        if self.dockwidget is not None:
            self.dockwidget.apply_language(self.current_language_code)


    # noinspection PyMethodMayBeStatic
    def tr(self, message):
        """Get the translation for a string using Qt translation API.

        We implement this ourselves since we do not inherit QObject.

        :param message: String for translation.
        :type message: str, QString

        :returns: Translated version of message.
        :rtype: QString
        """
        # noinspection PyTypeChecker,PyArgumentList,PyCallByClass
        return QCoreApplication.translate('CompassTraverseGis', message)


    def add_action(
        self,
        icon_path,
        text,
        callback,
        enabled_flag=True,
        add_to_menu=True,
        add_to_toolbar=True,
        status_tip=None,
        whats_this=None,
        parent=None):
        """Add a toolbar icon to the toolbar.

        :param icon_path: Path to the icon for this action. Can be a resource
            path (e.g. ':/plugins/foo/bar.png') or a normal file system path.
        :type icon_path: str

        :param text: Text that should be shown in menu items for this action.
        :type text: str

        :param callback: Function to be called when the action is triggered.
        :type callback: function

        :param enabled_flag: A flag indicating if the action should be enabled
            by default. Defaults to True.
        :type enabled_flag: bool

        :param add_to_menu: Flag indicating whether the action should also
            be added to the menu. Defaults to True.
        :type add_to_menu: bool

        :param add_to_toolbar: Flag indicating whether the action should also
            be added to the toolbar. Defaults to True.
        :type add_to_toolbar: bool

        :param status_tip: Optional text to show in a popup when mouse pointer
            hovers over the action.
        :type status_tip: str

        :param parent: Parent widget for the new action. Defaults None.
        :type parent: QWidget

        :param whats_this: Optional text to show in the status bar when the
            mouse pointer hovers over the action.

        :returns: The action that was created. Note that the action is also
            added to self.actions list.
        :rtype: QAction
        """

        icon = QIcon(icon_path)
        action = QAction(icon, text, parent)
        action.triggered.connect(callback)
        action.setEnabled(enabled_flag)

        if status_tip is not None:
            action.setStatusTip(status_tip)

        if whats_this is not None:
            action.setWhatsThis(whats_this)

        if add_to_toolbar:
            self.iface.addVectorToolBarIcon(action)

        if add_to_menu:
            self.iface.addPluginToVectorMenu(
                self.menu,
                action)

        self.actions.append(action)

        return action


    def initGui(self):
        """Create the menu entries and toolbar icons inside the QGIS GUI."""

        icon_path = os.path.join(os.path.dirname(__file__), 'icon.png')
        self.add_action(
            icon_path,
            text=self.tr(u'Compass Traverse GIS'),
            callback=self.run,
            parent=self.iface.mainWindow())

    #--------------------------------------------------------------------------

    def onClosePlugin(self):
        """Cleanup necessary items here when plugin dockwidget is closed"""

        self.dockwidget.closingPlugin.disconnect(self.onClosePlugin)
        self.pluginIsActive = False
        self.dockwidget = None


    def unload(self):
        """Removes the plugin menu item and icon from QGIS GUI."""

        if self.translator is not None:
            QCoreApplication.removeTranslator(self.translator)
            self.translator = None

        if self.dockwidget is not None:
            try:
                self.dockwidget.closingPlugin.disconnect(self.onClosePlugin)
            except Exception:  # nosec B110
                pass
            self.iface.removeDockWidget(self.dockwidget)
            self.dockwidget.close()
            self.dockwidget.deleteLater()
            self.dockwidget = None
        self.pluginIsActive = False

        for action in self.actions:
            self.iface.removePluginVectorMenu(
                self.tr(u'&Compass Traverse GIS'),
                action)
            self.iface.removeVectorToolBarIcon(action)

    #--------------------------------------------------------------------------

    def run(self):
        """Run method that loads and starts the plugin"""

        if not self.pluginIsActive:
            self.pluginIsActive = True

            if self.dockwidget is None:
                self.dockwidget = CompassTraverseGisDockWidget(
                    iface=self.iface,
                    plugin=self,
                )
            else:
                self.dockwidget._clear_preview_layers()
                self.dockwidget.apply_language(self.current_language_code)

            self.dockwidget.closingPlugin.connect(self.onClosePlugin)
            self.iface.addDockWidget(Qt.BottomDockWidgetArea, self.dockwidget)
            self.dockwidget.show()

        elif self.dockwidget is not None:
            self.dockwidget.setVisible(not self.dockwidget.isVisible())
